# Generated by Django 3.0.3 on 2020-03-08 02:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0002_auto_20200302_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 8, 2, 59, 6, 636100, tzinfo=utc), verbose_name='Дата с момента одолжения'),
        ),
    ]
