# Generated by Django 3.0.3 on 2020-08-05 10:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0005_auto_20200805_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 5, 10, 43, 7, 911966, tzinfo=utc), verbose_name='Дата с момента одолжения'),
        ),
    ]
