# Generated by Django 3.0.3 on 2020-08-09 02:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20200805_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='borrow_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 9, 2, 29, 55, 38665, tzinfo=utc), verbose_name='Дата с момента одолжения'),
        ),
    ]
