# Generated by Django 3.0.3 on 2020-08-09 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200809_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='borrow_date',
        ),
    ]
